tasks:
  install:
    image: "node:carbon"
    command: ["yarn"]
    args: ["install"]
  lint:
    image: "node:carbon"
    command: ["yarn"]
    args: ["lint"]
  flow:
    image: "node:carbon"
    command: ["yarn"]
    args: ["flow"]
  test:
    image: "node:carbon"
    command: ["yarn"]
    args: ["test"]
